version: "3"
services:

  my-carousel:
    restart: always
    build:
      context: ./
      dockerfile: local.Dockerfile
    container_name: my-carousel
    working_dir: /application/src
#    command: /bin/bash -c "npm i && npm run serve"
    command: /bin/bash -c "tail -f > /dev/null"
    volumes:
      - ./:/application/
    ports:
      - "4375:4200"
    networks:
        - my-carousel

networks:
    my-carousel:
        driver: bridge
        ipam:
            config:
                -   subnet: 11.21.0.0/16
